# Generated by Django 5.1.4 on 2025-01-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_remove_candidate_name_candidate_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='user',
        ),
        migrations.AddField(
            model_name='candidate',
            name='candidate_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
