# Generated by Django 5.1.4 on 2025-01-11 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_candidate_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='bio',
        ),
    ]
