# Generated by Django 5.1.4 on 2025-01-11 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_remove_candidate_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='user',
        ),
    ]
