# Generated by Django 5.1.4 on 2025-01-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0007_candidate_vote_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.IntegerField(max_length=25, unique=True)),
                ('web_mail', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
