# Generated by Django 5.1.4 on 2025-01-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0009_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='reg_no',
            field=models.IntegerField(unique=True),
        ),
    ]
